### ISSUE TITLE
Display Entire Filename on ROM Information Page

### ISSUE THREAD

**Issue by jesusburnsneon** [Polprzewodnikowy/N64FlashcartMenu#101]
### Description

I noticed that filenames are cutoff on the ROM information page if more than 54 characters and "..." is appended to the end.  Can the filename characters be wrapped on this part of the menu so the entire filename is displayed?  Including screenshot to show the issue.  With different versions/revisions of a ROM and character length cutoff, makes it hard to tell which is which without trimming the filename.

![Screenshot 2024-05-08 19-25-53 ed](https://github.com/Polprzewodnikowy/N64FlashcartMenu/assets/73132118/23240aaf-ae82-4ec7-a84a-1c61c530ac72)

**Comment by networkfusion** [comment]
Merged to main, so closing.
