### ISSUE TITLE
Hide macOS hidden files

### ISSUE THREAD

**Issue by BenoitCaron** [Polprzewodnikowy/N64FlashcartMenu#149]
### Description

I'm using a Mac to add my roms to the SD card. When using the SC64, the screen is now littered with macOS hidden files. All those files start with a "." 

### How to solve the problem

Do not show files starting with a ".". This could be either a default behavior or an option.

### Describe alternatives you've considered

Alternatively, the user can clean the directories of the SD card manually every time, but it's time consuming and prone to error.

**Comment by networkfusion** [comment]
Closing as not worth the effort.

**Comment by networkfusion** [comment]
Feel free to add the improvement via PR though.

**Comment by networkfusion** [comment]
On macOS, if you have extracted ROM's from zips run `dot_clean -m /Volumes/SummerCart` to clear those awful dotfiles so they are not shown in the menu.

**Comment by BenoitCaron** [comment]
Oh that's great! Thanks a lot :)

**Comment by networkfusion** [comment]
Fully fixed with #217
