### ISSUE TITLE
develop: Long filename with underscore breaks ROM filename rendering

### ISSUE THREAD

**Issue by ddund** [Polprzewodnikowy/N64FlashcartMenu#158]
### Description

Example with WRAP_WORD:
![Screenshot From 2024-11-09 16-30-29](https://github.com/user-attachments/assets/f6515eb6-9998-47b1-a2a2-80d06386f437)

with WRAP_ELLIPSES:
![Screenshot From 2024-11-09 16-29-36](https://github.com/user-attachments/assets/b9a48d17-d23b-45ef-864b-be5027cf5836)

Long filename without underscore:
![Screenshot From 2024-11-09 16-50-57](https://github.com/user-attachments/assets/7078166d-fdd8-44ee-b0d1-fdf1681328bf)

Example with a filename that does not extend the max width:
![Screenshot From 2024-11-09 16-48-25](https://github.com/user-attachments/assets/3b214b22-5883-44c0-9b0a-837987cad086)

I stumbled upon this when trying to improve the robustness of file name handling. I have not been able to determine the cause of this but a guess is that it could be something with how variable arguments is used in component_main_text_draw().

**Comment by networkfusion** [comment]
You will need to raise this on the n64brew discord and speak with one of the libdragon devs on the best way.

**Comment by networkfusion** [comment]
It is obviously doing things correctly in relation to underscores as that, as far as it is concerned, is a single word.

**Comment by ddund** [comment]
It seems like something is is going wrong in libdragon. If I replace component_main_text_draw() and call rdpq_text_printn() directly I get the same behaviour.

**Comment by rasky** [comment]
Fixed by https://github.com/DragonMinded/libdragon/commit/0c4e388851cabab52f421bff5e75e9dc3ab36c72
