### ISSUE TITLE
Kiosk Mode

### ISSUE THREAD

**Issue by forkymcforkface** [Polprzewodnikowy/N64FlashcartMenu#167]
### Description

Kiosk Mode would offer a simplified, secure interface, designed to get users into the game as quickly and easily as possible. 

Suggestions:

Menu Item Customization: Ability to hide certain or all non required menu items to streamline the UI.
Hide File Extensions: Option to hide file extensions in the game list view for a cleaner interface.
Direct Game Launch Options: Add option for kiosk mode to launch the game when A is pressed vs going into info screen.
Password Requirement: Ability to do key combo or password to enter/exit kiosk mode.

### How to solve the problem

streamline user experience for no technical people.

**Comment by networkfusion** [comment]
Closing as not planned. Feel free to create a PR when ready.
