### ISSUE TITLE
Support background images

### ISSUE THREAD

**Issue by networkfusion** [Polprzewodnikowy/N64FlashcartMenu#25]
### Description

Improves menu display

### How to solve the problem

Awaiting https://github.com/DragonMinded/libdragon/pull/401

**Comment by Polprzewodnikowy** [comment]
This is already implemented by https://github.com/Polprzewodnikowy/N64FlashcartMenu/commit/01ae2cef37d83cc609940dceec0daa9c76ca925d but it causes slowdown on screens with many characters displayed. Setting 30 FPS mode via https://github.com/DragonMinded/libdragon/pull/401 and adjusting button repeat timings should fix it.

**Comment by Polprzewodnikowy** [comment]
Closing this as 30 FPS frame limiter was implemented with different method. Now file list scrolling is smooth regardless of background presence or not.
