### ISSUE TITLE
Mark `.sav` files as hidden by default

### ISSUE THREAD

**Issue by networkfusion** [Polprzewodnikowy/N64FlashcartMenu#26]
### Description

Although we should work out the best way to handle "ROM saves" and folders, currently all files with `.sav` extensions are shown in the menu.

### How to solve the problem

Mark the file attribute as `hidden` by default.

### Describe alternatives you've considered

using a shadow directory structure for save paths. It would be less messy and easier to only backup saves.

**Comment by Polprzewodnikowy** [comment]
Currently not possible due to default FatFs settings in libdragon: https://github.com/DragonMinded/libdragon/blob/e3b756ecdac6200ff8b6ed255d8f9959137fd325/src/fatfs/ffconf.h#L55

**Comment by networkfusion** [comment]
I guess that the other way would be to just have a "browser filter" that would allow you to set whether any files that match the `.sav` extension are shown.
