### ISSUE TITLE
Add support for 64drive

### ISSUE THREAD

**Issue by Polprzewodnikowy** [Polprzewodnikowy/N64FlashcartMenu#3]
Help needed for confirming possibility of replacing `menu.bin` with libdragon produced binary. Original menu has different entrypoint `0x80002000` that could interfere with using libdragon entrypoint at `0x80000400`.

**Comment by networkfusion** [comment]
linked to #27

**Comment by Polprzewodnikowy** [comment]
Byte swapped ROM loading is currently broken, waiting for solution for this issue in libcart repository: https://github.com/devwizard64/libcart/issues/1

**Comment by Polprzewodnikowy** [comment]
Issue is fixed in the upstream repository, still waiting for patch to be implemented in libdragon

**Comment by networkfusion** [comment]
PR is awaiting merge: https://github.com/DragonMinded/libdragon/pull/410

**Comment by networkfusion** [comment]
Added to main, so closing.
