### ISSUE TITLE
Latest CI breaks forks

### ISSUE THREAD

**Issue by networkfusion** [Polprzewodnikowy/N64FlashcartMenu#32]
### Description

The action to upload the devcontainer breaks fork builds.

When building in a fork ( and PR's from them) the CI should just used the cached devcontainer and skip the step to upload it.

**Comment by Polprzewodnikowy** [comment]
Fixed in https://github.com/Polprzewodnikowy/N64FlashcartMenu/commit/1f0f8470db52789a2cd5ce6cada0fb0d9ca3fe33 and https://github.com/Polprzewodnikowy/N64FlashcartMenu/commit/558a690f3e47e7067ca1b0734a0f0990ccbac9b8
