### ISSUE TITLE
Use `unstable` libdragon branch

### ISSUE THREAD

**Issue by Polprzewodnikowy** [Polprzewodnikowy/N64FlashcartMenu#5]
Main roadblock is waiting for [this commit](https://github.com/DragonMinded/libdragon/commit/2413aacd5c3119fe9c3ef9b8fa5e4e965a15cc01) to be merged from `trunk` to `unstable` branch.
`unstable` branch has many new rendering features that would be very helpful for creating user interface.

**Comment by networkfusion** [comment]
Closing this as the menu is now using it.
