### ISSUE TITLE
CPU Exception at PC:00000000

### ISSUE THREAD

**Issue by Trevor89** [Polprzewodnikowy/N64FlashcartMenu#70]
### Firmware version of the flashcart

2

### Menu version used

latest (15/12/23)

### Description

When Load and Run any rom I get this CPU Exception.
I can load png's fine and navigate the menu, but I cannot load any game on my Everdrive V2.5

Backtrace:
<NULL_POINTER> [0x0000000]
flashcart_load_rom (...Menu/src/flashcart/flashcart.c:141)

### How to reproduce

Using Everdrive V2.5 PAL press A twice on any rom

### Expected behavior

load rom

**Comment by Polprzewodnikowy** [comment]
Everdrive V2.5 is not supported yet, there's pull request https://github.com/Polprzewodnikowy/N64FlashcartMenu/pull/44 open but progress on it unfortunately has slowed down. I can't work on it because I don't own this cartridge and can't do any testing myself.

**Comment by Trevor89** [comment]
Just doublechecked my cart and it says V2.0 (I cant remember what the differences were between 2 and 2.5)
firmware 2.33

**Comment by networkfusion** [comment]
I am going to close this as unsupported and covered by #4 
As pointed out, a potentially working example is in #44 and if it does not work, feel free to add comments in either of those.

**Comment by networkfusion** [comment]
Extra note: it might be worth ensuring that the menu warns the user that the current flashcart is unsupported in the main firmware, but not enough to re-open the issue.
