### ISSUE TITLE
adding settings menu 

### ISSUE THREAD

**Issue by TharathielCB** [Polprzewodnikowy/N64FlashcartMenu#74]
### Description

it would be helpful if you could add a setting menu which might refer to the config.ini
I am thinking about the following settings:
- info screen (-> FlashCartMenu Version; SummerCart64 firmware version; DD ipl files found/loaded, 
- setup the RTC (https://github.com/Polprzewodnikowy/N64FlashcartMenu/issues/57)
- force TV Type (https://github.com/Polprzewodnikowy/N64FlashcartMenu/issues/66 and https://github.com/Polprzewodnikowy/N64FlashcartMenu/pull/71)
- SC64 specific config options (https://github.com/Polprzewodnikowy/SummerCart64/blob/main/docs/04_config_options.md) 
e.g.: Button Mode, Change save type, CIC, ...

**Comment by networkfusion** [comment]
All of this is implemented, the only improvement required is to actually allow changing the settings.

**Comment by networkfusion** [comment]
Merged to main, so closing.
