### ISSUE TITLE
SD Access over USB

### ISSUE THREAD

**Issue by TharathielCB** [Polprzewodnikowy/N64FlashcartMenu#80]
### Description

Both my PC and my Laptop don't have an included (micro) SD-Card reader. So access to the SD-Card over the USB would be very helpful.

### How to solve the problem

Maybe implemented in the FlashcartMenu, or as a separate .N64 (Rom)
On the PC the file transfer could be over a CMD-command, GUI, or it's recognizing the Flashcard and it's SD-Card as a mass storage device.

Possible process flow to ensure the Flashcart/SummerCart(SC) and the PC don't try to read/write the SD-Card at the same time:
1. check connection to SC
2. requests current status of the SC
3. if SC is idle, lock SD access from SC side
4. read/write SD Card from PC -> cmd or explorer style
5. after finishing transfer, maybe verify (optional)
6. release SC and reboot for new SD scan

**Comment by networkfusion** [comment]
This was added in https://github.com/Polprzewodnikowy/SummerCart64/pull/90
