### ISSUE TITLE
Add sound effects

### ISSUE THREAD

**Issue by Polprzewodnikowy** [Polprzewodnikowy/N64FlashcartMenu#89]
### Description

It's a little boring scrolling through files in complete silence, let's add some sound effects in response to button presses.

### How to solve the problem

- find (or make) sound effects, permissible license is a must
- use `libdragon` tooling to embed sounds in the final ROM
- use `libdragon` API to load and play sound effects

**Comment by networkfusion** [comment]
Call for help added here: https://discord.com/channels/205520502922543113/205520502922543113/1197218871153807490

**Comment by networkfusion** [comment]
Perhaps someone wants to go through a website like this one: https://pixabay.com/sound-effects/search/button/ (given the license for them seem sensible (i.e. we can use them without attribution)) and compile a list good and related effects that can be used.

**Comment by networkfusion** [comment]
Merged to main, so closing.
